const $ = (s) => document.querySelector(s);
const root = $('#root');
const accountsKey = 'gym-progress-accounts';
const activeAccountKey = 'gym-progress-active-account';
const initialWorkouts = [
 {id:1,name:'Mój trening',date:'2026-06-30',duration:23,exercises:[ex('Bench Press',10,15),ex('Deadlift',10,15),ex('Squat',40,50)]},
 {id:2,name:'Mój trening',date:'2026-06-30',duration:15,exercises:[ex('Cable Row',12,2)]},
 {id:3,name:'Pull day',date:'2026-06-28',duration:42,exercises:[ex('Push-up',33,3)]},
 {id:4,name:'Akcesoria',date:'2026-06-26',duration:31,exercises:[ex('Dumbbell Fly',10,10)]}
];
const exerciseNames = ['Bench Press','Squat','Deadlift','Cable Row','Push-up','Dumbbell Fly','Hip Thrust','Shoulder Press'];
let user = null, tab = 'home', planning = false, loginError = '', syncError = '', isLoading = true, data = emptyData(), startedAt = 0, timer = null;
function ex(name, kg, reps){return {name,sets:[{kg,reps}]};}
function emptyData(){return {workouts:[],plans:{},draft:[]};}
function demoData(){return {workouts:initialWorkouts,plans:{},draft:[]};}
function readAccounts(){try{return JSON.parse(localStorage.getItem(accountsKey)||'[]');}catch(error){return [];}}
function writeAccounts(accounts){localStorage.setItem(accountsKey,JSON.stringify(accounts));}
function accountId(name){return `local-${Date.now()}-${name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,32)||'osoba'}`;}
function selectAccount(account){user=account;localStorage.setItem(activeAccountKey,account.id);isLoading=true;syncError='';render();loadUserData().catch(()=>{syncError='Nie udało się pobrać danych z backendu. Używamy pustego widoku tej osoby.';data=emptyData();}).finally(()=>{isLoading=false;render();});}
async function loadUserData(){const response=await fetch('/api/data',{headers:{'X-User-Id':user.id}});if(!response.ok)throw new Error('Nie udało się pobrać danych użytkownika.');const body=await response.json();data=body.data||emptyData();}
async function save(){if(!user)return;try{const response=await fetch('/api/data',{method:'PUT',headers:{'Content-Type':'application/json','X-User-Id':user.id},body:JSON.stringify(data)});if(!response.ok)throw new Error('Nie udało się zapisać danych.');syncError='';}catch(error){syncError='Nie udało się zsynchronizować danych z backendem.';}}
function icon(name){const icons={play:'▶',home:'⌂',history:'◷',plan:'▣',profile:'○',plus:'＋',x:'×',info:'ⓘ',left:'‹',right:'›',trend:'↗',pulse:'⌁',clock:'◴'};return icons[name]||'';}
function stats(){const records=data.workouts.flatMap(w=>w.exercises.flatMap(e=>e.sets.map(s=>({name:e.name,kg:s.kg,reps:s.reps,date:w.date}))));const best=Object.values(records.reduce((a,r)=>!a[r.name]||r.kg>a[r.name].kg?{...a,[r.name]:r}:a,{})).sort((a,b)=>b.kg-a.kg);return {total:data.workouts.length,weekCount:data.workouts.filter(w=>w.date>='2026-06-24').length,streak:1,volume:Math.round(records.reduce((s,r)=>s+r.kg*r.reps,0)/1000),records:best};}
function render(){if(!user){root.innerHTML=shell(login(),false);bindLogin();return;} if(isLoading){root.innerHTML=shell('<div class="login"><div class="logo">🏋️</div><h1>Ładowanie danych...</h1><p>Przygotowujemy osobny widok tej osoby.</p></div>',false);return;} root.innerHTML=shell((syncError?`<p class="error">${syncError}</p>`:'')+(planning?builder():views[tab](user)),!planning); bind();}
function shell(content,nav=true){return `<main class="phone"><section class="screen">${content}</section>${nav?navHtml():''}</main>`;}
function login(){const accounts=readAccounts();return `<div class="login"><div class="logo">🏋️</div><p class="eyebrow">Twój dziennik siłowni</p><h1>Kto teraz ćwiczy?</h1><p>Wybierz osobę albo dodaj nowe konto bez hasła. Każdy profil ma własne treningi, historię i plany.</p>${accounts.length?`<div class="account-list">${accounts.map(a=>`<button class="account" data-id="${a.id}"><span class="avatar small">${a.name[0]}</span><span>${a.name}</span></button>`).join('')}</div>`:'<p class="empty">Brak kont. Dodaj pierwszą osobę.</p>'}<form id="new-account" class="new-account"><input id="account-name" name="name" autocomplete="name" placeholder="Imię osoby" required><button type="submit">Stwórz nowe konto</button></form>${loginError?`<p class="error">${loginError}</p>`:''}</div>`;}
const views={home:(u)=>{const s=stats();return `<h1>Hej, ${(u.name||'Sportowcu').split(' ')[0]}</h1><p class="muted">${s.weekCount} treningi w tym tygodniu</p><button class="primary" id="start">${icon('play')} Rozpocznij trening</button>${statsHtml(s)}<h2>Rekordy</h2>${s.records.slice(0,3).map(recordCard).join('')}<h2>Ostatnie treningi</h2>${data.workouts.slice(0,3).map(workoutCard).join('')}`},history:()=>`<h1>Historia</h1>${data.workouts.map(workoutCard).join('')}`,plan:()=>`<h1>Plan treningowy</h1><div class="week"><button>${icon('left')}</button><b>Ten tydzień</b><button>${icon('right')}</button></div><div class="days">${['Nd\n29','Pn\n30','Wt\n1','Śr\n2','Cz\n3','Pt\n4','Nd\n5'].map((d,i)=>`<button class="day ${i===1?'active':''}" data-day="${d.replace('\n',' ')}">${d}</button>`).join('')}</div><h2>Plany tygodnia</h2>${Object.keys(data.plans).length?Object.entries(data.plans).map(([d,p])=>`<div class="card row"><b>${d}</b><strong>${p}</strong></div>`).join(''):'<p class="empty">Brak zaplanowanych treningów.<br>Kliknij dzień, aby dodać plan.</p>'}`,profile:(u)=>{const s=stats();const name=u.name||'Użytkownik';return `<h1>Profil</h1><div class="card profile"><div class="avatar">${name[0]}</div><div><b>${name}</b><p>Konto lokalne bez hasła</p></div></div><div class="stats"><div class="tile"><b>${s.total}</b><span>Treningi</span></div><div class="tile"><b>${s.weekCount}</b><span>Ten tydzień</span></div><div class="tile"><b>${s.volume}t</b><span>Objętość</span></div></div><h2>Rekordy osobiste</h2>${s.records.map(r=>`<div class="card row"><span><b>${r.name}</b><br><span>30 cze 2026</span></span><strong>${r.kg} kg<br><small>× ${r.reps} powt.</small></strong></div>`).join('')}<button class="secondary" id="logout">Zmień osobę</button>`}};
function statsHtml(s){return `<div class="stats"><div class="tile"><b>${s.total}</b><span>Treningów</span></div><div class="tile"><b>${s.weekCount}</b><span>Ten tydzień</span></div><div class="tile"><b>${s.streak}</b><span>Seria dni</span></div></div>`;}
function recordCard(r){return `<div class="card row"><b>${r.name}</b><strong>${r.kg} kg x ${r.reps}</strong></div>`;}
function workoutCard(w){const volume=w.exercises.flatMap(e=>e.sets).reduce((s,x)=>s+x.kg*x.reps,0);return `<div class="card"><div class="row"><b>${w.name}</b><span>Dzisiaj</span></div><p class="muted">${icon('pulse')} ${w.exercises.length} ćw. ${icon('trend')} ${volume} kg ${icon('clock')} ${w.duration}s</p></div>`;}
function builder(){return `<div class="top"><button id="close">${icon('x')}</button><span id="timer">${startedAt?'0s':'Planowanie'}</span><button id="begin">${startedAt?'Zakończ':'Rozpocznij'}</button></div><h1>Mój trening ✎</h1><p class="hint">${icon('info')} Dodaj ćwiczenia i serie, a następnie naciśnij „Rozpocznij” aby uruchomić stoper.</p>${data.draft.length?'':'<p class="empty">Dodaj ćwiczenia, aby zaplanować trening</p>'}${data.draft.map((e,i)=>`<div class="card"><b>${e.name}</b><div class="set"><input data-i="${i}" data-k="kg" type="number" value="${e.sets[0].kg}"> kg <input data-i="${i}" data-k="reps" type="number" value="${e.sets[0].reps}"> powt.</div></div>`).join('')}<button class="ghost" id="add">${icon('plus')} Dodaj ćwiczenie</button>`;}
function navHtml(){return `<nav>${[['home','⌂','Trening'],['history','◷','Historia'],['plan','▣','Plan'],['profile','○','Profil']].map(([id,ic,l])=>`<button class="nav ${tab===id?'on':''}" data-tab="${id}"><span>${ic}</span><small>${l}</small></button>`).join('')}</nav>`;}
function bindLogin(){document.querySelectorAll('.account').forEach(b=>b.onclick=()=>{const account=readAccounts().find(a=>a.id===b.dataset.id);if(account)selectAccount(account);}); const form=$('#new-account'); if(form)form.onsubmit=(event)=>{event.preventDefault();const input=$('#account-name');const name=input.value.trim();if(!name){loginError='Podaj imię osoby.';render();return;}const accounts=readAccounts();const account={id:accountId(name),name};accounts.push(account);writeAccounts(accounts);data=emptyData();selectAccount(account);};}
function bind(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();}); if($('#start')) $('#start').onclick=()=>{planning=true;data.draft=[];startedAt=0;save();render();}; if($('#logout')) $('#logout').onclick=()=>{user=null;localStorage.removeItem(activeAccountKey);data=emptyData();render();}; if($('#close')) $('#close').onclick=()=>{planning=false;clearInterval(timer);render();}; if($('#add')) $('#add').onclick=()=>{data.draft.push(ex(exerciseNames[data.draft.length%exerciseNames.length],10,10));save();render();}; document.querySelectorAll('input').forEach(i=>i.onchange=()=>{data.draft[i.dataset.i].sets[0][i.dataset.k]=+i.value;save();}); document.querySelectorAll('.day').forEach(d=>d.onclick=()=>{data.plans[d.dataset.day]='Mój trening';save();render();}); if($('#begin')) $('#begin').onclick=()=>{if(!data.draft.length)return;if(!startedAt){startedAt=Date.now();timer=setInterval(()=>{const t=$('#timer'); if(t)t.textContent=Math.floor((Date.now()-startedAt)/1000)+'s';},1000);render();}else{const duration=Math.max(1,Math.floor((Date.now()-startedAt)/1000));data.workouts.unshift({id:Date.now(),name:'Mój trening',date:new Date().toISOString().slice(0,10),duration,exercises:data.draft});data.draft=[];startedAt=0;planning=false;clearInterval(timer);save();render();}};}
const activeAccountId=localStorage.getItem(activeAccountKey);
const activeAccount=readAccounts().find(a=>a.id===activeAccountId);
if(activeAccount){selectAccount(activeAccount);}else{isLoading=false;data=demoData();render();}
